version: '3.4'

services:

  sqldata:
    container_name: sqldata
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123321Aa@
    volumes: 
      - microservice-sqldata:/var/opt/mssql
    # networks:
    #   - microservice-network

  rabbitmq:
    container_name: rabbitmq 
    ports:
      - "15672:15672"
      - "5672:5672"

  orderservice:
    container_name: microservices-order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OrderConnection=Server=localhost,1433;Initial Catalog=MicroserviceOrderDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true
      - MicroServiceAddress:Product:Uri=https://localhost:11002 
      - Identity:Uri=http://localhost:7018
      - Identity:Audience=OrderService
      - Identity:Scopes:OrdersManagement=OrdersManagement
      - Identity:Scopes:GetOrders=GetOrders
      # - RabbitMq:HostName=amqp://guest:guest@rabbitmq:5672
      # - RabbitMq:HostName=amqp://guest:guest@rabbitmq:5672
      # - RabbitMq:HostName=http://localhost:5672
      - RabbitMq:Uri=amqp://guest:guest@rabbitmq:5672
      - RabbitMq:HostName=localhost
      - RabbitMq:Port=5672
      - RabbitMq:UserName=ghost 
      - RabbitMq:Password=ghost
    ports:
      - "7002:7002"
    depends_on:
      - sqldata
      - identityservice
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basketservice:
    container_name: microservices-basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - BasketConnection=Server=localhost,1433;Initial Catalog=MicroserviceBasketDB;User Id=SA;Password=123321Aa@
      - MicroServiceAddress:Discount:Uri=http://localhost:8002
    ports:
      - "6002:6002"
    depends_on:
      - sqldata
      - identityservice
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discountservice:
    container_name: microservices-discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DiscountConnection=Server=localhost,1433;Initial Catalog=MicroserviceDiscountDB;User Id=SA;Password=123321Aa@
    ports:
      - "8002:8002"
    depends_on:
      - sqldata
      - identityservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  productservice:
    container_name: microservices-product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ProductConnection=Server=localhost,1433;Initial Catalog=MicroserviceProductDB;User Id=SA;Password=123321Aa@
      - Identity:Uri=http://localhost:7018
      - Identity:Audience=ProductService
      - Identity:Scopes:ProductsManagement=ProductsManagement
    ports:
      - "11002:11002"
    depends_on:
      - sqldata
      - identityservice
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  paymentservice.endpoint:
    container_name: microservices-payment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PaymentConnection=Server=localhost,1433;Initial Catalog=MicroservicePaymentDB;User Id=SA;Password=123321Aa@
    ports:
      - "10002:10002"
    depends_on:
      - sqldata
      - identityservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identityservice:
    container_name: microservices-identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AspIdentityConnection=Server=localhost,1433;Initial Catalog=MicroserviceAspIdentityDB;User Id=SA;Password=123321Aa@
      - WebFrontend:Uri=https://localhost:44328
      - AdminFrontend:Uri=https://localhost:7298
    ports:
      - "7018:7018"
    depends_on:
      - sqldata
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  apigateway.admin:
    container_name: microservices-apigateway.admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Identity:Uri=http://localhost:7018
      - Identity:Audience=ApiGatewayAdmin
    ports:
      - "11023:11022"
    depends_on:
      - sqldata
      - identityservice
      - orderservice
      - discountservice
      - basketservice
      - productservice
      - paymentservice.endpoint
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  apigateway.forweb:
    container_name: microservices-apigateway.forweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Identity:Uri=http://localhost:7018
      - Identity:Audience=apiGatewayForWeb
    ports:
      - "10023:10023"
    depends_on:
      - sqldata
      - identityservice
      - orderservice
      - discountservice
      - basketservice
      - productservice
      - paymentservice.endpoint
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservices.admin.frontend:
    container_name: microservices.admin.frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Identity:Uri=http://localhost:7018
    ports:
      - "7298:7298"
    depends_on:
      - apigateway.admin
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservices.web.frontend:
    container_name: microservices.web.frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - MicroserviceAddress:ApiGatewayForWeb:Uri=https://localhost:10023
      - Identity:Uri=http://localhost:7018
    ports:
      - "44328:44328"
    depends_on:
      - apigateway.forweb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  microservice-sqldata:
    external: false

