apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice-deployment
  labels:
    app: identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - name: identityservice
          image: mkhalesiir/microserviceidentityservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: AspIdentityConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroserviceAspIdentityDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: WebFrontend__Uri
              value: http://webfrontend-clusterip-srv:44330
            # - name: AdminFrontend__Uri
            #   value: http://${EXTERNAL_DNS_NAME_OR_IP}:7298
---
apiVersion: v1
kind: Service
metadata:
  name: identityservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: identityservice
  ports:
  - name: identityservice
    protocol: TCP
    port: 7020
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identityservice-srv
spec:
  type: NodePort
  selector:
    app: identityservice
  ports:
    - name: identityservice
      protocol: TCP
      port: 7020
      targetPort: 80
      nodePort: 31720