apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqldata-deployment
  labels:
    app: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldata
  template:
    metadata:
      labels:
        app: sqldata
    spec:
      containers:
        - name: sqldata
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1434
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: ACCEPT_EULA
              value: "Y"
            # - name: sqldata-secret
            #   value: MTIzMzIxQWFA
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldata-secret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: sqldatadb
      volumes:
      - name: sqldatadb
        persistentVolumeClaim:
          claimName: sqldata-claim
            
---
apiVersion: v1
kind: Service
metadata:
  name: sqldata-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: sqldata
  ports:
  - name: sqldata
    protocol: TCP
    port: 1434
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: sqldata-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: sqldata
  ports:
  - protocol: TCP
    port: 1434
    targetPort: 1433
