# apiVersion: apiextensions.k8s.io
# kind: CustomResourceDefinition
# apiVersion: app/v1
# kind: Deployment
# metadata:
#   name: platforms-depl
# spec:
#   replicas: 1
#   selector: 
#     matchLabels: 
#       app: productservice
#   template: 
#     metadata: 
#       labels: 
#         app: productservice
#     spec: 
#       containers:
#         - name: productservice
#           image: productservice


# apiVersion: "app/v1"
# kind: Deployment
# metadata:
#   name: platforms-depl
# spec:
#   cronSpec: "* * * * */5"
#   image: productservice

# apiVersion: "stable.example.com/v1"
# kind: CronTabs
# metadata:
#   name: my-new-cron-object
# spec:
#   cronSpec: "* * * * */5"
#   image: my-awesome-cron-image


# apiVersion: apiextensions.k8s.io/v1
# kind: CustomResourceDefinition
# metadata:
#   # name must match the spec fields below, and be in the form: <plural>.<group>
#   name: crontabs.stable.example.com
# spec:
#   # group name to use for REST API: /apis/<group>/<version>
#   group: stable.example.com
#   # list of versions supported by this CustomResourceDefinition
#   versions:
#     - name: v1
#       # Each version can be enabled/disabled by Served flag.
#       served: true
#       # One and only one version must be marked as the storage version.
#       storage: true
#       schema:
#         openAPIV3Schema:
#           type: object
#           properties:
#             spec:
#               type: object
#               properties:
#                 cronSpec:
#                   type: string
#                 image:
#                   type: string
#                 replicas:
#                   type: integer
#   # either Namespaced or Cluster
#   scope: Namespaced
#   names:
#     # plural name to be used in the URL: /apis/<group>/<version>/<plural>
#     plural: crontabs
#     # singular name to be used as an alias on the CLI and for display
#     singular: crontab
#     # kind is normally the CamelCased singular type. Your resource manifests use this.
#     kind: CronTab
#     # shortNames allow shorter string to match your resource on the CLI
#     shortNames:
#     - ct

