apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigatewayadmin-deployment
  labels:
    app: apigatewayadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigatewayadmin
  template:
    metadata:
      labels:
        app: apigatewayadmin
    spec:
      containers:
        - name: apigatewayadmin
          image: microservices/apigatewayadmin
          # image: mkhalesiir/microservicesapigatewayadmin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Identity__Uri
              value: http://kubernetes.docker.internal:31720
            - name: Identity__Audience
              value: ApiGatewayAdmin
---
apiVersion: v1
kind: Service
metadata:
  name: apigatewayadmin-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: apigatewayadmin
  ports:
  - name: apigatewayadmin
    protocol: TCP
    port: 11025
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apigatewayadmin-srv
spec:
  type: NodePort
  selector:
    app: apigatewayadmin
  ports:
    - name: apigatewayadmin
      protocol: TCP
      port: 11025
      targetPort: 80
      nodePort: 31125