apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketservice-deployment
  labels:
    app: basketservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketservice
  template:
    metadata:
      labels:
        app: basketservice
    spec:
      containers:
        - name: basketservice
          image: basketservice
          # image: mkhalesiir/microservicesbasketservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ProductConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroserviceBasketDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: RabbitMq__Uri
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: MicroServiceAddress__Discount__Uri
              value: http://microservices-discount.api
            - name: MicroServiceAddress__DiscountGrpc__Uri
              value: http://microservices-discount.api:81
            - name: Identity__Uri
              value: http://172.20.144.1:31720
            - name: Identity__Audience
              value: BasketService
---
apiVersion: v1
kind: Service
metadata:
  name: basketservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: basketservice
  ports:
  - name: basketservice
    protocol: TCP
    port: 6005
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basketservice-srv
spec:
  type: NodePort
  selector:
    app: basketservice
  ports:
    - name: basketservice
      protocol: TCP
      port: 6005
      targetPort: 80
      nodePort: 31605