apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountservice-deployment
  labels:
    app: discountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountservice
  template:
    metadata:
      labels:
        app: discountservice
    spec:
      containers:
        - name: discountservice
          image: microservices/discountservice
          # image: mkhalesiir/discountservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: DiscountConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroserviceDiscountDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: Kestrel__Endpoints__HTTP__Url
              value: http://0.0.0.0:80
            - name: Kestrel__Endpoints__GRPC__Url
              value: http://0.0.0.0:81
            - name: Kestrel__Endpoints__GRPC__Protocols
              value: Http2
---
apiVersion: v1
kind: Service
metadata:
  name: discountservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: discountservice
  ports:
  - name: discountservice
    protocol: TCP
    port: 8005
    targetPort: 80
  # - name: discountservicegrpc
  #   protocol: TCP
  #   port: 8005
  #   targetPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: discountservice-srv
spec:
  type: NodePort
  selector:
    app: discountservice
  ports:
    - name: discountservice
      protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 31805
    # - name: discountservicegrpc
    #   protocol: TCP
    #   port: 8005
    #   targetPort: 81
    #   nodePort: 31805