apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: microservices/orderservice
          # image: mkhalesiir/microservicesorderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: OrderConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroserviceOrderDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: Identity__Uri
              value: http://172.20.144.1:31720
            - name: Identity__Audience
              value: OrderService
            - name: Identity__Scopes__OrdersManagement
              value: OrdersManagement
            - name: Identity__Scopes__GetOrders
              value: GetOrders
            - name: RabbitMq__Uri
              value: amqp://guest:guest@rabbitmq-service:5672
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
  - name: orderservice
    protocol: TCP
    port: 7005
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-srv
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - name: orderservice
      protocol: TCP
      port: 7005
      targetPort: 80
      nodePort: 31705