apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: microservices/paymentserviceendpoint
          # image: mkhalesiir/microservicespaymentservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: PaymentConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroservicePaymentDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: Identity__Uri
              value: http://kubernetes.docker.internal:31720
            - name: Identity__Audience
              value: PaymentService
            - name: RabbitMq__Uri
              value: amqp://guest:guest@rabbitmq-clusterip-service:5672
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: paymentservice
    protocol: TCP
    port: 10004
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-srv
spec:
  type: NodePort
  selector:
    app: paymentservice
  ports:
    - name: paymentservice
      protocol: TCP
      port: 10004
      targetPort: 80
      nodePort: 31104