apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
  labels:
    app: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: mkhalesiir/microserviceproductservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ProductConnection
              value: Server=sqldata-clusterip-service,1434;Database=MicroserviceProductDB;User Id=sa;password=123321Aa@;Encrypt=False;TrustServerCertificate=true;
            - name: RabbitMq__Uri
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: Identity__Uri
              value: http://172.20.144.1:31720
              # value: http://172.20.144.1:31720
            - name: Identity__Audience
              value: ProductService
            - name: Identity__Scopes__ProductsManagement
              value: ProductsManagement
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: productservice
  ports:
  - name: productservice
    protocol: TCP
    port: 11004
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-srv
spec:
  type: NodePort
  selector:
    app: productservice
  ports:
    - name: productservice
      protocol: TCP
      port: 11004
      targetPort: 80
      nodePort: 31114