# first version
# version: '3'
# services:
#   productservice:
#     build: .
#     ports: 
#       - "8080:80"
#       - "8081:443"
#     environment: 
#       ASPNETCORE_RULES: ""
#       ASPNETCORE_HTTP_PORT: ""
#       ASPNETCORE_ENVIRONMENT: "Development"
#     # volumes:
#     #  - $"{APPDATA/microsoft/UserSecrets\:/root/.microsoft/UserSecrets}"
#     #  - $"{USERPROFILE}\.aspnet\htpps:/root/.aspnet/https/"

version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 'Str0ngPa$$w0rd'
      # MSSQL_PID: 'Express'
      # MSSQL_PID: 'Enterprise'
    ports:
      - '1401:1433'
  productservice:
    build: .
    #environment:
    # DBServer: 'ms-sql-server'
    # - DATABASE_PUBLIC_URL=ms-sql-server

    # ASPNETCORE_RULES: ""
    # ASPNETCORE_HTTP_PORT: ""
    # ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - '8080:80'

#Server name is '91e9a35b3961'. This is an informational message only. No user action is required.
#Did not find an existing master data file /var/opt/mssql/data/master.mdf, copying the missing default master and other system database files. If you have moved the database location, but not moved the database files, startup may fail. To repair: shutdown SQL Server, move the master database to configured location, and restart.
